# Generated by Django 5.1.6 on 2025-03-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='applied_on',
            field=models.DateField(),
        ),
    ]
