# Generated by Django 5.1.6 on 2025-03-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_leave_applied_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='applied_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
