# Generated by Django 5.1.6 on 2025-03-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_leave_applied_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='Leave_type',
            field=models.CharField(choices=[('SL', 'Sick Leave'), ('CL', 'Casual Leave'), ('ML', 'Medical Leave'), ('UL', 'Unpaid Leave')], default='CL', max_length=2),
        ),
        migrations.AddField(
            model_name='leave',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='Leave_Documents/'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Half day', 'Half day')], default='Half day', max_length=20),
        ),
    ]
