# Generated by Django 5.1.6 on 2025-03-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_leave_leave_type_leave_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='applied_on',
            field=models.DateField(),
        ),
    ]
