# Generated by Django 5.1.6 on 2025-04-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendance_date_alter_leave_applied_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='applied_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
