# Generated by Django 5.1.6 on 2025-03-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_submitted',
            name='Attachments',
            field=models.FileField(blank=True, null=True, upload_to='Submitted_Task/'),
        ),
        migrations.AlterField(
            model_name='teamtasksubmitted',
            name='Attachments',
            field=models.FileField(blank=True, null=True, upload_to='TeamSubmitted_Task/'),
        ),
    ]
