# Generated by Django 5.1.2 on 2025-03-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0004_alter_task_submitted_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_submitted',
            name='score',
            field=models.IntegerField(choices=[(3, 'Bad'), (5, 'Average'), (8, 'Good'), (10, 'Very Good')], null=True),
        ),
        migrations.AlterField(
            model_name='teamtasksubmitted',
            name='score',
            field=models.IntegerField(choices=[(3, 'Bad'), (5, 'Average'), (8, 'Good'), (10, 'Very Good')], null=True),
        ),
    ]
