# Generated by Django 5.1.6 on 2025-04-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0005_alter_task_submitted_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task_assigned',
            options={'ordering': [models.Case(models.When(status='pending', then=models.Value(1)), models.When(status='In Progress', then=models.Value(2)), models.When(status='submited', then=models.Value(3)), models.When(status='complete', then=models.Value(4)), output_field=models.IntegerField())]},
        ),
        migrations.AlterModelOptions(
            name='task_submitted',
            options={'ordering': [models.Case(models.When(status='pending', then=models.Value(1)), models.When(status='Approved', then=models.Value(2)), models.When(status='Rejected', then=models.Value(3)), output_field=models.IntegerField())]},
        ),
        migrations.AlterModelOptions(
            name='teamtaskassign',
            options={'ordering': [models.Case(models.When(status='pending', then=models.Value(1)), models.When(status='In Progress', then=models.Value(2)), models.When(status='submited', then=models.Value(3)), models.When(status='complete', then=models.Value(4)), output_field=models.IntegerField())]},
        ),
        migrations.AlterModelOptions(
            name='teamtasksubmitted',
            options={'ordering': [models.Case(models.When(status='pending', then=models.Value(1)), models.When(status='Approved', then=models.Value(2)), models.When(status='Rejected', then=models.Value(3)), output_field=models.IntegerField())]},
        ),
    ]
