# Generated by Django 5.1.2 on 2025-03-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leader', '0002_alter_subtasksubmit_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtasksubmit',
            name='score',
            field=models.CharField(choices=[(2.5, 'Bad'), (5, 'Average'), (7.5, 'Good'), (10, 'Very Good')], max_length=4, null=True),
        ),
    ]
