# Generated by Django 5.1.2 on 2025-03-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leader', '0003_subtasksubmit_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtasksubmit',
            name='score',
            field=models.IntegerField(choices=[(3, 'Bad'), (5, 'Average'), (8, 'Good'), (10, 'Very Good')], null=True),
        ),
    ]
