# Generated by Django 5.1.6 on 2025-02-22 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_team_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default='Employee', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.role'),
        ),
    ]
