# Generated by Django 5.1.6 on 2025-02-21 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Created_on', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('Created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Team_Created_By', to=settings.AUTH_USER_MODEL)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='department.department')),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Team_leader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('Emp', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='leader.team')),
            ],
        ),
    ]
