# Generated by Django 5.1.6 on 2025-03-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtasksubmit',
            name='Attachments',
            field=models.FileField(blank=True, null=True, upload_to='TeamSubSubmitted_Task/'),
        ),
    ]
