# Generated by Django 5.1.6 on 2025-02-21 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('leader', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('leader',), name='unique_active_leader'),
        ),
        migrations.AddConstraint(
            model_name='team_member',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('Emp',), name='unique_active_employee'),
        ),
    ]
