# Generated by Django 5.1.6 on 2025-02-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leader', '0002_team_unique_active_leader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='Description',
            field=models.CharField(default=' Not Provided ', max_length=200),
        ),
    ]
