# Generated by Django 5.1.6 on 2025-02-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leader', '0003_team_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Description',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
