# Generated by Django 5.1.6 on 2025-02-21 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leader', '0005_alter_team_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Team_leader', to=settings.AUTH_USER_MODEL),
        ),
    ]
