# Generated by Django 5.1.6 on 2025-02-21 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leader', '0006_alter_team_leader'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='team',
            name='unique_active_leader',
        ),
    ]
