# Generated by Django 5.1.6 on 2025-02-22 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leader', '0007_remove_team_unique_active_leader'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='team_member',
            name='unique_active_employee',
        ),
    ]
