# Generated by Django 5.1.6 on 2025-02-15 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_on', models.DateField(auto_created=True)),
                ('Task', models.TextField(max_length=1000)),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('status', models.CharField(choices=[('complete', 'complete'), ('pending', 'pending'), ('Not completed', 'Not completed')], default='pending', max_length=20)),
                ('Assigened_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Task_assignment_by', to=settings.AUTH_USER_MODEL)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Task_assignment_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
