# Generated by Django 5.1.6 on 2025-02-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='given_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
