# Generated by Django 5.1.6 on 2025-02-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_alter_task_given_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='End_date',
            new_name='deadline',
        ),
        migrations.RemoveField(
            model_name='task',
            name='Start_date',
        ),
        migrations.AddField(
            model_name='task',
            name='Attachments',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('complete', 'complete'), ('pending', 'pending'), ('in Progress', 'in Progress'), ('Not completed', 'Not completed')], default='pending', max_length=20),
        ),
    ]
