# Generated by Django 5.1.6 on 2025-03-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_task_submitted_score_teamtasksubmitted_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_submitted',
            name='score',
            field=models.CharField(choices=[(2.5, 'Bad'), (5, 'Average'), (7.5, 'Good'), (10, 'Very Good')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='teamtasksubmitted',
            name='score',
            field=models.CharField(choices=[(2.5, 'Bad'), (5, 'Average'), (7.5, 'Good'), (10, 'Very Good')], max_length=4, null=True),
        ),
    ]
