# Generated by Django 5.1.6 on 2025-02-17 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_rename_end_date_task_deadline_remove_task_start_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Assigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task', models.TextField(max_length=1000)),
                ('Attachments', models.FileField(upload_to='Task_Assign/')),
                ('deadline', models.DateField()),
                ('given_on', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('complete', 'complete'), ('pending', 'pending'), ('in Progress', 'in Progress'), ('Not completed', 'Not completed')], default='pending', max_length=20)),
                ('Assigened_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Task_assignment_by', to=settings.AUTH_USER_MODEL)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Task_assignment_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task_Submitted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attachments', models.FileField(upload_to='Submitted_Task/')),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('comments', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('pending', 'pending')], default='pending', max_length=20)),
                ('Task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.task_assigned')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Task_Submmited_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
