# Generated by Django 5.1.6 on 2025-02-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0004_task_assigned_task_submitted_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_assigned',
            name='Attachments',
            field=models.FileField(blank=True, null=True, upload_to='Task_Assign/'),
        ),
    ]
