# Generated by Django 5.1.6 on 2025-02-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0005_alter_task_assigned_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_assigned',
            name='status',
            field=models.CharField(choices=[('complete', 'complete'), ('pending', 'pending'), ('In Progress', 'In Progress'), ('Not completed', 'Not completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='task_submitted',
            name='comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
