# Generated by Django 5.1.6 on 2025-02-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0006_alter_task_assigned_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_assigned',
            name='status',
            field=models.CharField(choices=[('complete', 'complete'), ('submited', 'submited'), ('pending', 'pending'), ('In Progress', 'In Progress'), ('Not completed', 'Not completed')], default='pending', max_length=20),
        ),
    ]
