# Generated by Django 5.1.6 on 2025-02-21 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0008_alter_task_submitted_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_submitted',
            name='Task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Task.task_assigned'),
        ),
    ]
